### PR TITLE
Add comments to elements

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR adds comments to elements using `typescript`'s parser to enhance the docs:

- top-level comment for the class
- `*Attributes` property comments
- comments for getters and setters

### CODE REVIEW

**Comment by jaredjj3** [comment]
@eliot-akira, after this PR is submitted, would you PTAL at https://stringsync.github.io/musicxml/? The "Files changed" section has so many changes, the page essentially crashes :\

Feel free to comment here or submit an issue.

**Comment by eliot-akira** [comment]
Wonderful! I looked around the docs pages and all comments are there in the generated elements, as far as I could see. I like how you solved it in `getElementComments()` using the TypeScript compiler. That really creates a helpful reference, to be able to get an overview of all MusicXML elements, comments, properties, methods.

Oh, I found a missing closing backtick for inline code. Running ``grep -Rn "\`<[a-z]*> " .`` in `src/lib/elements`, here are other places I found.

```
./Alter.ts:9: * The `<alter> element represents chromatic alteration in number of semitones (e.g., -1 for flat, 1 for sharp). Decimal
./Rest.ts:11: * The `<rest> element indicates notated rests or silences. A `<rest> element is usually empty, but placement on the
./Backup.ts:7: * The `<backup> element
./Backup.ts:9: * Parent elements: `<measure> (partwise), `<part> (timewise)
./Backup.ts:11: * The `<backup> and `<forward> elements are required to coordinate multiple voices in one part, including music on
./Backup.ts:12: * multiple staves. The `<backup> element is generally used to move between voices and staves. Thus it does not include
./Backup.ts:13: * `<voice> or `<staff> elements. Duration values should always be positive, and should not cross measure boundaries or
./Backup.ts:14: * mid-measure changes in the `<divisions> value.
```

**Comment by jaredjj3** [comment]
Good catch! That's an easy fix I can do this weekend.

**Comment by jaredjj3** [comment]
The backticks should be fixed now.

```sh
% grep -Rn "\`<[a-z]*> " src/lib/elements
%
```

**Comment by eliot-akira** [comment]
Looks great!

**Pull request merged**
