### PR TITLE
Add TypeDoc to generate documentation

### PR DESCRIPTION
**Pull request by eliot-akira**
Here's an idea to use [TypeDoc](https://typedoc.org/) to generate documentation of all exported classes.

First try looks like this, served by GitHub Pages on my forked branch under `./docs`. https://eliot-akira.github.io/musicxml/

### CODE REVIEW

**Review by jaredjj3 — APPROVED** [review]
This looks amazing! This is waaay better than grokking through the generated file or Intellisense.

**Comment by jaredjj3** [comment]
@eliot-akira, do you know of a way we can preserve the comments in `src/lib` ([example](https://github.com/stringsync/musicxml/blob/26edaff389e611070ed08c55c7d22f71a8134156/src/lib/elements/Accord.ts#L7-L16))? If so, one of us should do it in a downstream PR.

**Comment by eliot-akira** [comment]
> preserve the comments in src/lib ([example](https://github.com/stringsync/musicxml/blob/26edaff389e611070ed08c55c7d22f71a8134156/src/lib/elements/Accord.ts#L7-L16))

Oh I see what you mean, I'll try to improve that. I imagine the TypeDoc configuration needs to specify correct [entryPoints](https://typedoc.org/options/input/#entrypoints) or maybe different [entryPointStrategy](https://typedoc.org/options/input/#entrypointstrategy).

**Comment by eliot-akira** [comment]
Changing around the TypeDoc config, the closest I could get was to include the source of the generated elements as an additional entry point, `src/lib/elements/index.ts`.

image

But it lists them under `lib/elements`, and not as clear as having a single entry point `index.ts`.

image

---

There's probably a way to extract Docblock comments from `lib/elements` and copy them into `generated/elements.ts`.

If I were to go down that rabbit hole (haha), I would use the parser library [`@typescript-eslint/typescript-estree`](https://typescript-eslint.io/packages/typescript-estree/), which is used by ESLint and Prettier - or maybe using the TypeScript compiler itself is simpler; then walk the AST to gather comments above classes, types, etc. The code generation script in `src/scripts/generate.ts` can include that data in the right places.

**Comment by jaredjj3** [comment]
Thanks for digging into that. I think [@typescript-eslint/typescript-estree](https://typescript-eslint.io/packages/typescript-estree/) is the right way forward here. I'll try to hack something together this week. For now, I'll merge this in and setup GitHub Pages. Thanks again for contributing!

**Pull request merged**
